connectionReferences:
  - connectionReferenceLogicalName: sample_adminupdatesagent.cr.shared_commondataserviceforapps
    connectorId: /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps
